### ISSUE TITLE
[feature request] (more) lightweight preview

### ISSUE THREAD

**Issue by arily** [111116/webosu#39]
在sayo的镜像站看到了
http://osugame.online/preview.html?sid=746506&bid=1573320
这样的预览界面
我想在sb服（一个osu私服）的前端里嵌入铺面预览。

![image](https://user-images.githubusercontent.com/10007589/83466648-b2419d80-a4b2-11ea-8713-7420ad26d613.png)
[在线预览](https://next.ppy.sb/beatmap-preview-test/#/beatmapsets/746506/1573320)

我尝试过使用iframe嵌入，有几个小问题：

- 失焦后note会全部miss
- 没有办法暂停
- Master音量默认有些大

希望可以做一个更轻便的铺面预览功能

**Comment by 111116** [comment]
你可以把预览网页和它引用的所有资源嵌入到您的网站中，因为网页是纯前端的。
然后作如下修改：
`preview.html` 中删除调用 `wtf()` 以恢复暂停功能
`preview.html` 中 `function f()` 里设置你想要的游戏设定（如音量）
`playback.js` 中删除对blur事件的响应，以禁用失焦时暂停
你还可以在其他情况下调用 `playback` 的 `pause`/`resume` 方法以自定义暂停控制

**Comment by 111116** [comment]
现在的预览界面其实是随便赶出来的。如果你能做出一个像视频播放器那样适合embed的小窗，欢迎提Pull request.  拖进度条应该也有办法实现的。

**Comment by arily** [comment]
好的 我去研究一下

**Comment by arily** [comment]
大概熟悉了下程序

有点小建议
如果可以的话建议用Vue或React之类的去生成overlays或者所有ui，
至少可以用 https://github.com/developit/htm 这个repo去创建DOM
会比用document.createElement可读性高很多。

**Comment by 111116** [comment]
确实，代码比较乱，不想动了

**Comment by arily** [comment]
某些代码看起来有些像打包后的代码。
不知道是否有打包前的代码呢

**Comment by 111116** [comment]
比如？

**Comment by arily** [comment]
比如那些在用require.js的代码

**Comment by 111116** [comment]
Closing obsolete issue. Please reopen if issue persists.
