### ISSUE TITLE
Wrong slider SV bug

### ISSUE THREAD

**Issue by OliBomby** [111116/webosu#40]
If you play the map "The Guinea Pig Is In Your Mind" on the top difficulty, then the last slider of the map has a velocity which is way too low. It causes the map to go on for a full 40 seconds after the song ended. This slider isn't so slow on the normal osu!

**Comment by 111116** [comment]
Please provide beatmapset ID

**Comment by 111116** [comment]
If you take a close look at the `.osu` file you'll see that the timing point at start of the last slider indicates a 1/50 velocity, followed by another timing point a few frames later. I actually have no idea how osu! interprets that...

**Comment by OliBomby** [comment]
I do know how osu! interprets that. SV from greenlines is always clipped between 0.10x and 10x, so the greenline with 1/50x SV should only have the effect of 0.10x SV. 

Timing and SV starts exactly on the time of the timingpoint, so if the slider is 1 millisecond before the timingpoint it will use the previous timingpoint. However for hitsound related stuff on timingpoints (like volume) it goes into effect 5 milliseconds before the timingpoint, so an object 5 milliseconds before the timingpoint can still get the volume from it. You can get the correct hitsound behaviour by just offsetting the timingpoints with -5 milliseconds. Note that this offset is only for hitsounds.

**Comment by 111116** [comment]
I've clamped the greenline SV b904501.
This fix will be included in the next update. (scripts are hosted on other's server so I can't update them very regularly)
Hitsound timing is yet to fix
