### ISSUE TITLE
Skip function doesn't work

### ISSUE THREAD

**Issue by HelloWorldZTR** [111116/webosu#49]
系统 macOS 10.13.6 浏览器是 Google Chrome 84.0.4147.105（正式版本） （64 位）
随便试了几个谱面(前奏长度大于30秒)，后来改了快捷键还是不行
希望能增加跳过前奏的视觉提示~

**Comment by 111116** [comment]
#42 @chocovon

**Comment by HelloWorldZTR** [comment]
对不起哈，是我看错了

**Comment by HelloWorldZTR** [comment]
抱歉是我没熟悉操作方式，给大家添麻烦了
