### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by PalmTigre** [111116/webosu#51]
It's as if I can hear one part of the music, but the other part, usually the actually singing, can barely be heard, it also messes with the hit sounds.

**Comment by 111116** [comment]
never heard of it. can you elaborate on that? also what browser & OS are you using?

**Comment by PalmTigre** [comment]
It's been working up until this morning. I'm on a chromebook, if that's what you are asking.

**Comment by 111116** [comment]
Then I'm afraid there's nothing I can do about it. Maybe try restarting or something?

**Comment by PalmTigre** [comment]
Welp, okay. Have a good day.
