### ISSUE TITLE
Game wont download the songs

### ISSUE THREAD

**Issue by LittleFriskYT** [111116/webosu#53]
Everytime i try to download a song it just freezes the download or it wont download at all. not eve the pictures on the beatmaps will show up. it worked yesterday but now today it stopped working for me. 
![Screenshot 2020-09-15 at 9 19 48 AM](https://user-images.githubusercontent.com/71330728/93215603-9d70d900-f734-11ea-8e39-04f7a935cfb8.png)

**Comment by 111116** [comment]
Sorry, something is temporarily down #52

**Comment by LittleFriskYT** [comment]
Do you know if it will fix itself or no???

**Comment by 111116** [comment]
OK I guess it works now, although I've no idea what's gone wrong
