### ISSUE TITLE
Maps won't load.

### ISSUE THREAD

**Issue by Teme05** [111116/webosu#60]
Last few days always when I try to load a beatmap it says "Beatmap download failed. Please retry later." I have no idea why because I still see people playing on the website. I tried loading map on multiple devices but it just says the same. I hope it gets fixed soon.

**Comment by 111116** [comment]
have you tried other maps?

**Comment by Teme05** [comment]
Yes I have. I even tried maps that were just played minutes ago but still don't work...

**Comment by chocovon** [comment]
Check if you can connect to this link : https://txy1.sayobot.cn/beatmaps/download/mini/

**Comment by Teme05** [comment]
It says 404 Not Found...

**Comment by zCri** [comment]
I think sayobot removed the beatmap mirror, in the network debugger tool i see 404 every request it makes to fetch a map, maybe you could use bloodcat? But idk if it has an api, the website is chinese and i dont know chinese

**Comment by 111116** [comment]
please `ping txy1.sayobot.cn` and provide the IP address shown

**Comment by zCri** [comment]
> 
> 
> please `ping txy1.sayobot.cn` and provide the IP address shown
144.172.126.89 doned

**Comment by 111116** [comment]
can you retry now? provide your location if still not working

**Comment by zCri** [comment]
works fine now, thanks

**Comment by pvrzz** [comment]
I am having the same problem!
Pinged and got the IP 144.172.126.145

(2/24/2022 3:36PM)
