### ISSUE TITLE
Keeps removing songs in my Favorites

### ISSUE THREAD

**Issue by Lvl50prod** [111116/webosu#63]
Almost every time I go onto osugame.online I go to my favorites and Nothing is there then i forget what I had in there I was just ignoring it before but now it's actually pissing me off. (and also I think you should make it where people can log in with their github accounts so they can save everything and all that)

**Comment by 111116** [comment]
your favorites are supposed to be stored locally in your browser, using localstorage which should be supported by any modern browser. Make sure you’re not using private browing or something. report any console error (F12 to open console)

**Comment by 111116** [comment]
Closing obsolete issue. Please reopen if issue persists.
